### ISSUE TITLE
ImportError: No module named rospkg

### ISSUE THREAD

**Issue by zhudelong** [ros-naoqi/nao_virtual#13]
I installed the simulation environment of Nao Players in RobCup [ https://github.com/ros-naoqi/nao_virtual ] Everything is okay but cannot find Rospkg. I reinstalled with many methods but still not work. In fact, the pkg is there exactly and if I import rospkg in python client, the error occurs. I wonder if there is some problem about Python. Hope someone can help me. Thank you very much

Traceback (most recent call last): File "/opt/ros/indigo/share/xacro/xacro.py", line 60, in <module> import xacro File "/opt/ros/indigo/lib/python2.7/dist-packages/xacro/__init__.py", line 45, in <module> from roslaunch import substitution_args File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/__init__.py", line 48, in <module> import rospkg

ImportError: No module named rospkg

while processing /opt/ros/indigo/share/nao_description/launch/upload_nao.launch: Invalid tag: Cannot load command parameter [robot_description]: command [/opt/ros/indigo/share/xacro/xacro.py /opt/ros/indigo/share/nao_description/urdf/naoV40_generated_urdf/nao_robot.xacro] returned with code [1].

**Comment by zhudelong** [comment]
I find out the reason. since i installed the conda and the original path was rewrite.
